# is a organization repository
organization: false

# site title
title: nkypy's land

# user name or organization name
user: nkypy

# issue repository
repository: blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: d6b0faa5e86#424918352fa32fb22d156d1e1d65a

# posts per page
perpage: 8
